# -*- coding: utf-8 -*-
# Generated by Django 2.1.2 on 2018-11-27 04:37
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_cumulative_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalnumcomments',
            name='num_comments',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='totalscore',
            name='score',
            field=models.BigIntegerField(),
        ),
    ]
