# -*- coding: utf-8 -*-
# Generated by Django 2.1.2 on 2019-02-15 15:58
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_total_bigint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subreddit',
            old_name='average_gilded',
            new_name='average_gilded_gold',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='gilded',
        ),
        migrations.AddField(
            model_name='comment',
            name='gilded_gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='gilded_platinum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='gilded_silver',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='gilded_gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='gilded_platinum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='gilded_silver',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='average_gilded_platinum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='average_gilded_silver',
            field=models.FloatField(default=0),
        ),
    ]