# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-05-19 05:24
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_gildings'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comments_admin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='comments_gilded_gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='comments_gilded_platinum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='comments_gilded_silver',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='comments_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='comments_op',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='comments_polarity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='comments_root',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='comments_special',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='comments_subjectivity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='num_sample_comments',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
