# -*- coding: utf-8 -*-
# Generated by Django 2.1.7 on 2019-05-19 23:12
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_submission_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='submission',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
